# Generated by Django 3.0.5 on 2020-05-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='dificulty',
            new_name='difficulty',
        ),
    ]
